easy_admin:
    user:
        name_property_path: 'username'
    entities:
        User:
            class: App\Entity\User
            disabled_actions: ['new']
            form:
                fields: ['email', { property: 'username', label: "Nom d'utilisateur" }]
            list:
                fields: ['email', { property: 'username', label: "Nom d'utilisateur" }]
            search:
                fields: ['email', 'username']