easy_admin:
    site_name: '<strong>CovidCentral - EasyAdmin</strong>'
    user:
        name_property_path: 'username'
    entities:
        User:
            class: App\Entity\User
            disabled_actions: ['new']
            form:
                fields: ['email', { property: 'username', label: "Nom d'utilisateur" }, { property: 'firstname', label: "Nom" }, { property: 'lastname', label: "Prénom" }, { property: 'tel', label: "Tel" }, { property: 'city', label: "Ville" }]
            list:
                fields: ['email', { property: 'username', label: "Nom d'utilisateur" }, { property: 'firstname', label: "Nom" }, { property: 'lastname', label: "Prénom" }, { property: 'tel', label: "Tel" }, { property: 'city', label: "Ville" }]
            search:
                fields: ['email', 'username']
    design:
        assets:
            css:
                - 'bundles/easyadmin/app.scss'
                - 'bundles/easyadmin/app.css'